table Dim_Product
	lineageTag: 5323b111-8d96-4ff4-b373-50bb9e1e54d4

	column Product_Code
		dataType: string
		lineageTag: d2b52b72-20b8-4078-a250-be028f82c03c
		summarizeBy: none
		sourceColumn: Product_Code

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 3e1b8930-c860-4c6c-a418-116d0e8ae554
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 71b675a6-f147-489b-99b5-bf355c7e50bd
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Vendor_Price
		dataType: int64
		formatString: 0
		lineageTag: b257a49a-cf37-4c84-b777-d79d90523556
		summarizeBy: sum
		sourceColumn: Vendor_Price

		annotation SummarizationSetBy = Automatic

	column Customer_Price
		dataType: int64
		formatString: 0
		lineageTag: 2bb43cf9-eb51-437f-9592-611ad37b9505
		summarizeBy: sum
		sourceColumn: Customer_Price

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 46a70bc1-760f-4e38-9e7f-b15621ec1a46
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub_Category
		dataType: string
		lineageTag: d41a04ca-27f3-4d65-ba19-5526af1c4112
		summarizeBy: none
		sourceColumn: Sub_Category

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(DataFolder & "\Sales-Growth-Sample-Data.xlsx"), null, true),
				    #"Product master_sheet" = Source{[Item="Product master",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Product master_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 1)) otherwise false),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Bottom Rows", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_Code", type text}, {"Product_Name", type text}, {"Brand", type text}, {"Vendor_Price", Int64.Type}, {"Customer_Price", Int64.Type}, {"Category", type text}, {"Sub_Category", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

