table 'Fact_Combined Sales'
	lineageTag: fe05c948-678b-4c3f-91ab-00b110e1f8f9

	column Date_Order
		dataType: dateTime
		formatString: Long Date
		lineageTag: d3daf2ca-e66b-43d4-bc2e-2ac2d10f5081
		summarizeBy: none
		sourceColumn: Date_Order

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Date_Delivered
		dataType: dateTime
		formatString: Long Date
		lineageTag: 430b1ae5-1879-4909-b877-d57ba026e735
		summarizeBy: none
		sourceColumn: Date_Delivered

		variation Variation
			isDefault
			relationship: e68217c2-e85b-4e30-aeed-f9c969a0c8e1
			defaultHierarchy: LocalDateTable_7248fdb7-e70f-461b-a3dc-b56ee2644a02.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Order_Number
		dataType: string
		lineageTag: faf0a621-d49f-4d09-b18d-c5a0331ae3a3
		summarizeBy: none
		sourceColumn: Order_Number

		annotation SummarizationSetBy = Automatic

	column Product_Id
		dataType: string
		lineageTag: 8685ec24-8a62-40b7-a9a5-b081b160449b
		summarizeBy: none
		sourceColumn: Product_Id

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: int64
		formatString: 0
		lineageTag: 67cf9fee-aedd-49a9-9fda-b2105c8de1a0
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: 52b9ea83-ecbc-4e26-92a6-89a1924c309c
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Vendor_Id
		dataType: string
		lineageTag: ad8bc59b-9318-4429-9176-35c68b1279db
		summarizeBy: none
		sourceColumn: Vendor_Id

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: 134387a4-e068-499d-8f60-7e0c8fc18ba0
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column Channle_ID
		dataType: string
		lineageTag: fb203ddc-5f1f-42fa-ab9f-dfb2727eee8b
		summarizeBy: none
		sourceColumn: Channle_ID

		annotation SummarizationSetBy = Automatic

	column Discount_%
		dataType: double
		lineageTag: 45422dd3-54ce-4d38-a059-8f168f5c666a
		summarizeBy: sum
		sourceColumn: Discount_%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact_Combined Sales' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Data\Sales-Growth-Sample-Data.xlsx"), null, true),
				    #"Amazon Vendor Sales_Sheet" = Source{[Item="Amazon Vendor Sales",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Amazon Vendor Sales_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date_Order", type date}, {"Date_Packed", type date}, {"Date_Delivered", type date}, {"Order_Number", type text}, {"Product_Id", type text}, {"Qty", Int64.Type}, {"Product_Name", type text}, {"Vendor_Id", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Date_Packed"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns", {"Product_Id"}, Dim_Product, {"Product_Code"}, "Dim_Product master", JoinKind.LeftOuter),
				    #"Expanded Dim_Product master" = Table.ExpandTableColumn(#"Merged Queries", "Dim_Product master", {"Vendor_Price"}, {"Dim_Product master.Vendor_Price"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded Dim_Product master",{{"Dim_Product master.Vendor_Price", "Price"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Channle_ID", each 1),
				    #"Appended Query" = Table.Combine({#"Added Custom", #"Fact_On-Site Customer Orders (2)"})
				in
				    #"Appended Query"

	annotation PBI_ResultType = Table

